### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bapowell** [ikyriak/ConsistentApiResponseErrors#22]
Would you mind [adding a license](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to your repo?

_By the way, thank you for writing this package/lib, and documenting it well._

**Comment by ikyriak** [comment]
Thank you, @bapowell , for your feedback and for reminding me to add a license 👍 
I am including the MIT License.
Have a nice day.
